### ISSUE TITLE
request doesn't match cuando la pregunta no existe 

### ISSUE THREAD

**Issue by luisza** [solvo/derb#14]
Debería dar un error 404 not found y no este error

![pantallazo](https://cloud.githubusercontent.com/assets/7146904/19199334/bedf8c80-8c80-11e6-8633-0b212f002283.png)

es recomendable utilizar get_object_or_404  shortcut en 

![pantallazo-1](https://cloud.githubusercontent.com/assets/7146904/19199356/e53853e4-8c80-11e6-89e1-ba989f57ce21.png)

**Comment by maucrodriguez** [comment]
Corregido en boolean_question, simple_text_question, integer_question  y unique_selection_question en la rama issue_fixes
