### ISSUE TITLE
Incorrecta forma de llamar URLs 

### ISSUE THREAD

**Issue by luisza** [solvo/derb#5]
Utilizar {% url 'url name' %}  en lugar de quemar la ruta en código

![pantallazo](https://cloud.githubusercontent.com/assets/7146904/19162286/75a212e4-8bb4-11e6-8a27-a01541f1e8db.png)

### Revisar una forma de manejar los namespace
No necesariamente se va a llamar report_builder el namespace, por lo que debería cambiar según sea el namespace al que se llame

![pantallazo](https://cloud.githubusercontent.com/assets/7146904/19162381/e36fd90a-8bb4-11e6-9d31-9e558f1c6912.png)

Consultar a Mauricio para Buscar una solución

**Comment by maucrodriguez** [comment]
Corregido en issue_fixes
