### ISSUE TITLE
Eliminar lógica de JS de los templates

### ISSUE THREAD

**Issue by luisza** [solvo/derb#6]
Debe eliminar la lógica de javascript de los templates, llevando se el código hace un archivo en static/js  el block de js debe servir para llamar este archivo y pasarle los parámetros necesarios solamente. 
Es una mala práctica mezclas html y js en los mismos archivos.
También como recomendación puede usar los $.data() para hacer marcado en tags de información relevante.

![pantallazo](https://cloud.githubusercontent.com/assets/7146904/19162597/b5d5ef56-8bb5-11e6-8114-8df4ee1dd67a.png)

**Comment by maucrodriguez** [comment]
Corregido en issue_fixes
