### ISSUE TITLE
Loop infinito si se envía un no entero a get_catalog_display_fields

### ISSUE THREAD

**Issue by solvo** [solvo/derb#7]
Para probar esta parte hay que modificar el contenido del selectbox de catalog y ponerle cualquier carácter en las opciones de value.

![pantallazo](https://cloud.githubusercontent.com/assets/15187146/19162916/10106342-8bb7-11e6-9769-4d8b17b463ac.png)

También sucede si le pasamos un número que sea más grande que el número de catálogos existentes

Este error no afecta el funcionamiento normal del sistema, pero abre una puerta a ataques DoS

**Comment by maucrodriguez** [comment]
Corregido en issue_fixes
