### ISSUE TITLE
Inadecuada form de implementar funcionalidad

### ISSUE THREAD

**Issue by luisza** [solvo/derb#8]
Algunas cosas a tomar en cuenta:

-  L24  tiene () pero no Hereda de nadie
-  L31 posible error si no existe el key y posible error de index out of range
-  Hace una lista, luego la transforma un una tupla (2 recorridos a la lista) donde solo se requiere uno, pensar en hacer un iterador en lugar de una tupla, para esto puede usar en L41 yield (value, text) 

![pantallazo](https://cloud.githubusercontent.com/assets/7146904/19163188/434a8dd6-8bb8-11e6-8d31-a27c7f684ef9.png)

**Comment by maucrodriguez** [comment]
Corregido en issue_fixes
